/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesSalesforceTransformationRouteImport } from './routes/services.salesforce-transformation'
import { Route as ServicesNetsuiteConsultingRouteImport } from './routes/services.netsuite-consulting'
import { Route as ServicesMaAdvisoryRouteImport } from './routes/services.ma-advisory'
import { Route as ServicesEnterpriseImplementationsRouteImport } from './routes/services.enterprise-implementations'
import { Route as ServicesCertiniaConsultingRouteImport } from './routes/services.certinia-consulting'
import { Route as ServicesBpoTransformationRouteImport } from './routes/services.bpo-transformation'
import { Route as ServicesAiDigitalTransformationRouteImport } from './routes/services.ai-digital-transformation'
import { Route as IndustriesTechnologyRouteImport } from './routes/industries.technology'
import { Route as IndustriesPublicSectorRouteImport } from './routes/industries.public-sector'
import { Route as IndustriesPrivateEquityRouteImport } from './routes/industries.private-equity'
import { Route as IndustriesHealthcareRouteImport } from './routes/industries.healthcare'
import { Route as IndustriesFinancialServicesRouteImport } from './routes/industries.financial-services'

const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSalesforceTransformationRoute =
  ServicesSalesforceTransformationRouteImport.update({
    id: '/services/salesforce-transformation',
    path: '/services/salesforce-transformation',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesNetsuiteConsultingRoute =
  ServicesNetsuiteConsultingRouteImport.update({
    id: '/services/netsuite-consulting',
    path: '/services/netsuite-consulting',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesMaAdvisoryRoute = ServicesMaAdvisoryRouteImport.update({
  id: '/services/ma-advisory',
  path: '/services/ma-advisory',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesEnterpriseImplementationsRoute =
  ServicesEnterpriseImplementationsRouteImport.update({
    id: '/services/enterprise-implementations',
    path: '/services/enterprise-implementations',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesCertiniaConsultingRoute =
  ServicesCertiniaConsultingRouteImport.update({
    id: '/services/certinia-consulting',
    path: '/services/certinia-consulting',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesBpoTransformationRoute =
  ServicesBpoTransformationRouteImport.update({
    id: '/services/bpo-transformation',
    path: '/services/bpo-transformation',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesAiDigitalTransformationRoute =
  ServicesAiDigitalTransformationRouteImport.update({
    id: '/services/ai-digital-transformation',
    path: '/services/ai-digital-transformation',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndustriesTechnologyRoute = IndustriesTechnologyRouteImport.update({
  id: '/industries/technology',
  path: '/industries/technology',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesPublicSectorRoute = IndustriesPublicSectorRouteImport.update({
  id: '/industries/public-sector',
  path: '/industries/public-sector',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesPrivateEquityRoute = IndustriesPrivateEquityRouteImport.update({
  id: '/industries/private-equity',
  path: '/industries/private-equity',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesHealthcareRoute = IndustriesHealthcareRouteImport.update({
  id: '/industries/healthcare',
  path: '/industries/healthcare',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesFinancialServicesRoute =
  IndustriesFinancialServicesRouteImport.update({
    id: '/industries/financial-services',
    path: '/industries/financial-services',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/insights': typeof InsightsRoute
  '/industries/financial-services': typeof IndustriesFinancialServicesRoute
  '/industries/healthcare': typeof IndustriesHealthcareRoute
  '/industries/private-equity': typeof IndustriesPrivateEquityRoute
  '/industries/public-sector': typeof IndustriesPublicSectorRoute
  '/industries/technology': typeof IndustriesTechnologyRoute
  '/services/ai-digital-transformation': typeof ServicesAiDigitalTransformationRoute
  '/services/bpo-transformation': typeof ServicesBpoTransformationRoute
  '/services/certinia-consulting': typeof ServicesCertiniaConsultingRoute
  '/services/enterprise-implementations': typeof ServicesEnterpriseImplementationsRoute
  '/services/ma-advisory': typeof ServicesMaAdvisoryRoute
  '/services/netsuite-consulting': typeof ServicesNetsuiteConsultingRoute
  '/services/salesforce-transformation': typeof ServicesSalesforceTransformationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/insights': typeof InsightsRoute
  '/industries/financial-services': typeof IndustriesFinancialServicesRoute
  '/industries/healthcare': typeof IndustriesHealthcareRoute
  '/industries/private-equity': typeof IndustriesPrivateEquityRoute
  '/industries/public-sector': typeof IndustriesPublicSectorRoute
  '/industries/technology': typeof IndustriesTechnologyRoute
  '/services/ai-digital-transformation': typeof ServicesAiDigitalTransformationRoute
  '/services/bpo-transformation': typeof ServicesBpoTransformationRoute
  '/services/certinia-consulting': typeof ServicesCertiniaConsultingRoute
  '/services/enterprise-implementations': typeof ServicesEnterpriseImplementationsRoute
  '/services/ma-advisory': typeof ServicesMaAdvisoryRoute
  '/services/netsuite-consulting': typeof ServicesNetsuiteConsultingRoute
  '/services/salesforce-transformation': typeof ServicesSalesforceTransformationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/insights': typeof InsightsRoute
  '/industries/financial-services': typeof IndustriesFinancialServicesRoute
  '/industries/healthcare': typeof IndustriesHealthcareRoute
  '/industries/private-equity': typeof IndustriesPrivateEquityRoute
  '/industries/public-sector': typeof IndustriesPublicSectorRoute
  '/industries/technology': typeof IndustriesTechnologyRoute
  '/services/ai-digital-transformation': typeof ServicesAiDigitalTransformationRoute
  '/services/bpo-transformation': typeof ServicesBpoTransformationRoute
  '/services/certinia-consulting': typeof ServicesCertiniaConsultingRoute
  '/services/enterprise-implementations': typeof ServicesEnterpriseImplementationsRoute
  '/services/ma-advisory': typeof ServicesMaAdvisoryRoute
  '/services/netsuite-consulting': typeof ServicesNetsuiteConsultingRoute
  '/services/salesforce-transformation': typeof ServicesSalesforceTransformationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/careers'
    | '/contact'
    | '/insights'
    | '/industries/financial-services'
    | '/industries/healthcare'
    | '/industries/private-equity'
    | '/industries/public-sector'
    | '/industries/technology'
    | '/services/ai-digital-transformation'
    | '/services/bpo-transformation'
    | '/services/certinia-consulting'
    | '/services/enterprise-implementations'
    | '/services/ma-advisory'
    | '/services/netsuite-consulting'
    | '/services/salesforce-transformation'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/careers'
    | '/contact'
    | '/insights'
    | '/industries/financial-services'
    | '/industries/healthcare'
    | '/industries/private-equity'
    | '/industries/public-sector'
    | '/industries/technology'
    | '/services/ai-digital-transformation'
    | '/services/bpo-transformation'
    | '/services/certinia-consulting'
    | '/services/enterprise-implementations'
    | '/services/ma-advisory'
    | '/services/netsuite-consulting'
    | '/services/salesforce-transformation'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/careers'
    | '/contact'
    | '/insights'
    | '/industries/financial-services'
    | '/industries/healthcare'
    | '/industries/private-equity'
    | '/industries/public-sector'
    | '/industries/technology'
    | '/services/ai-digital-transformation'
    | '/services/bpo-transformation'
    | '/services/certinia-consulting'
    | '/services/enterprise-implementations'
    | '/services/ma-advisory'
    | '/services/netsuite-consulting'
    | '/services/salesforce-transformation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  InsightsRoute: typeof InsightsRoute
  IndustriesFinancialServicesRoute: typeof IndustriesFinancialServicesRoute
  IndustriesHealthcareRoute: typeof IndustriesHealthcareRoute
  IndustriesPrivateEquityRoute: typeof IndustriesPrivateEquityRoute
  IndustriesPublicSectorRoute: typeof IndustriesPublicSectorRoute
  IndustriesTechnologyRoute: typeof IndustriesTechnologyRoute
  ServicesAiDigitalTransformationRoute: typeof ServicesAiDigitalTransformationRoute
  ServicesBpoTransformationRoute: typeof ServicesBpoTransformationRoute
  ServicesCertiniaConsultingRoute: typeof ServicesCertiniaConsultingRoute
  ServicesEnterpriseImplementationsRoute: typeof ServicesEnterpriseImplementationsRoute
  ServicesMaAdvisoryRoute: typeof ServicesMaAdvisoryRoute
  ServicesNetsuiteConsultingRoute: typeof ServicesNetsuiteConsultingRoute
  ServicesSalesforceTransformationRoute: typeof ServicesSalesforceTransformationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/salesforce-transformation': {
      id: '/services/salesforce-transformation'
      path: '/services/salesforce-transformation'
      fullPath: '/services/salesforce-transformation'
      preLoaderRoute: typeof ServicesSalesforceTransformationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/netsuite-consulting': {
      id: '/services/netsuite-consulting'
      path: '/services/netsuite-consulting'
      fullPath: '/services/netsuite-consulting'
      preLoaderRoute: typeof ServicesNetsuiteConsultingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/ma-advisory': {
      id: '/services/ma-advisory'
      path: '/services/ma-advisory'
      fullPath: '/services/ma-advisory'
      preLoaderRoute: typeof ServicesMaAdvisoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/enterprise-implementations': {
      id: '/services/enterprise-implementations'
      path: '/services/enterprise-implementations'
      fullPath: '/services/enterprise-implementations'
      preLoaderRoute: typeof ServicesEnterpriseImplementationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/certinia-consulting': {
      id: '/services/certinia-consulting'
      path: '/services/certinia-consulting'
      fullPath: '/services/certinia-consulting'
      preLoaderRoute: typeof ServicesCertiniaConsultingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/bpo-transformation': {
      id: '/services/bpo-transformation'
      path: '/services/bpo-transformation'
      fullPath: '/services/bpo-transformation'
      preLoaderRoute: typeof ServicesBpoTransformationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/ai-digital-transformation': {
      id: '/services/ai-digital-transformation'
      path: '/services/ai-digital-transformation'
      fullPath: '/services/ai-digital-transformation'
      preLoaderRoute: typeof ServicesAiDigitalTransformationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/technology': {
      id: '/industries/technology'
      path: '/industries/technology'
      fullPath: '/industries/technology'
      preLoaderRoute: typeof IndustriesTechnologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/public-sector': {
      id: '/industries/public-sector'
      path: '/industries/public-sector'
      fullPath: '/industries/public-sector'
      preLoaderRoute: typeof IndustriesPublicSectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/private-equity': {
      id: '/industries/private-equity'
      path: '/industries/private-equity'
      fullPath: '/industries/private-equity'
      preLoaderRoute: typeof IndustriesPrivateEquityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/healthcare': {
      id: '/industries/healthcare'
      path: '/industries/healthcare'
      fullPath: '/industries/healthcare'
      preLoaderRoute: typeof IndustriesHealthcareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/financial-services': {
      id: '/industries/financial-services'
      path: '/industries/financial-services'
      fullPath: '/industries/financial-services'
      preLoaderRoute: typeof IndustriesFinancialServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  InsightsRoute: InsightsRoute,
  IndustriesFinancialServicesRoute: IndustriesFinancialServicesRoute,
  IndustriesHealthcareRoute: IndustriesHealthcareRoute,
  IndustriesPrivateEquityRoute: IndustriesPrivateEquityRoute,
  IndustriesPublicSectorRoute: IndustriesPublicSectorRoute,
  IndustriesTechnologyRoute: IndustriesTechnologyRoute,
  ServicesAiDigitalTransformationRoute: ServicesAiDigitalTransformationRoute,
  ServicesBpoTransformationRoute: ServicesBpoTransformationRoute,
  ServicesCertiniaConsultingRoute: ServicesCertiniaConsultingRoute,
  ServicesEnterpriseImplementationsRoute:
    ServicesEnterpriseImplementationsRoute,
  ServicesMaAdvisoryRoute: ServicesMaAdvisoryRoute,
  ServicesNetsuiteConsultingRoute: ServicesNetsuiteConsultingRoute,
  ServicesSalesforceTransformationRoute: ServicesSalesforceTransformationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
